### ISSUE TITLE
Large words are getting native compiled

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#117]
ACCEPT, which SEE says is size 321 in decimal, was being natively compiled.  It will soon have the NN (never native) flag added to stop that for other reasons, but I don't believe Tali should be trying to native compile such a large word.  I haven't checked any other large words yet for native compiling.

**Comment by SamCoVT** [comment]
Tali compiles other large words natively as well.

I'm assuming the issue is here in native_words.asm in `COMPILE,`:
```
_check_size_limit:
                ; Native compile is a legal option, but we need to see what
                ; limit the user set for size
                lda tmptos
                sta 0,x
                lda tmptos+1
                sta 1,x

                jsr xt_wordsize         ; ( nt -- u )

                ; We implicitly assume that we don't want to compile anything
                ; greater than 255 bytes, so we only deal with LSB
                clc
                cmp nc_limit            ; user-defined limit
                bcc _compile_as_code

                jmp _compile_as_jump    ; too far for BRA
```
It looks to me like it calls xt_wordsize to get the size of the word, but then never loads the accumulator with the resulting value (in 0,X) before doing a CMP.  I haven't checked this in the monitor yet, but I'm assuming that xt_wordsize doesn't also leave the LSB in A when it returns.  I'm out of time to work on this, but I figured I would record my findings to help narrow down the issue.  I'm not entirely sure if `COMPILE,` is the right word to be in, but it does look like a possible issue.

**Comment by SamCoVT** [comment]
Mike B. on the 6502.org forum already found this bug back in March, and even posted a solution while he was shrinking some of Tali's subroutines.
http://forum.6502.org/viewtopic.php?f=9&t=2926&start=105#p58990
My plan is to try out his version and see if it clears this up when I finally get some free time.
His post also mentions some other possible bugs in CONSTANT, so I'll check those out too and add an issue if needed.

**Comment by SamCoVT** [comment]
#120 has Mike B's fixes and codeshrinks.  I had to do a line-by-line comparison to add some of his codeshrink changes because some of the details (like how many bytes the underflow detection uses, and how the underflow error message is printed) had changed since he originally wrote the fix.

This has been tested in py65mon, and I was also able to run the entire test suite (except the cycle testing) on my real hardware.  I only had to slow down the long string test to give Tali2 enough time to print the really long string at 9600bps before continuing to send tests.

I believe Tali has been natively compiling almost everything for a while, as I'm seeing a lot more free memory now.  On the bright side, I suppose that means your native compiling code has been thoroughly tested, as we've run the entire test suite that way.

**Comment by scotws** [comment]
Sorry for the delay, I finally upgraded my system to Ubuntu 18.04 LTS. Should get to this today. Thanks for this, and glad to know the native compiling code works, though I would have liked to have it a different way :-).
