### ISSUE TITLE
nc-limit is treated as an 8-bit value in COMPILE_COMMA

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#121]
While fixing up #117 I noticed that only the lower byte of nc-limit is used.  There was a note in the comments about implicitly expecting a value of 255 or less.  The original code was only comparing the LSBs.  I modified the code so it actually checks the MSB of the wordsize for zero before comparing the LSB of the wordsize to the LSB of nc-limit.  I've checked the documentation and I don't see any mention of a limit of 255 for nc-limit mentioned.

I see two paths forward:

[A] nc-limit should be checked for all 16-bits.  It's only a few extra assembly instructions.

[B] The documentation should be updated to mention the 255 byte limit.

Thoughts?  I think I'm leaning towards A, even though I think setting nc-limit over 100 is rather silly.

**Comment by scotws** [comment]
I think you're right, A should be the way to do it, especially because I tend to rant about software that tries to be move clever than the user -- if people want to set the nc-limit over 100, who are we to tell them not to.

**Comment by SamCoVT** [comment]
Sounds good to me.  I checked the rest of the native compiling code, and it uses MOVE to do the actual copying, so it should be 16-bit safe for words over 255 bytes long.  The length parameter passed to MOVE looks like the entire 16-bit value from WORDSIZE (modifed for underflow, etc), so it looks like I only need to modify where the WORDSIZE value is checked against nc-limit.

**Comment by SamCoVT** [comment]
I tested #122 with a small word, and with `COMPILE,` which has a size of 283, one of the few words over 255 bytes that isn't flagged NeverNative.  

Speaking of that...  shouldn't COMPILE_COMMA be flagged NN?  It has an absolute jump in it, so if it were native compiled, the new version would jump back into the old version in the _compile_as_jump case.  It won't hurt anything if that happens, but I was under the impression that words with JMP (as opposed to BRA) instructions in them would be NN.  If that's true, you may want to just flag COMPILE_COMMA as NN in the headers.
