### ISSUE TITLE
Documentation Error in DUMP

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#125]
I saw in one of the recent commits (adding ASCII display to dump) the comment:
```
; ## DUMP ( addr u -- ) "Display a memory region"
; ## "dump"  tested  ANS tools
        ; """DUMP's exact output is defined as "implementation dependent".
        ; This is in assembler because it is 
        ; useful for testing and development, so we want to have it work
        ; as soon as possible. Uses TMP3 <------
        ; """
```
The comment says that it uses TMP3, however the code below it seems to be using tmp2 instead.  I suspect this is just a typo, or that you had to switch to tmp2 and missed the comment.

**Comment by scotws** [comment]
Thanks, yep, silly typo.
