### ISSUE TITLE
Add test for ALLOT releasing memory

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#128]
Note there is no official ANSI test for stuff like **-100 ALLOT**. We need to test case when **ALLOT** releases a small amount (say, 10 bytes), then if it re-allots the same sum (should be same number as beginning). Also, need to release more than we have for Dictionary and end up with DROP still working.

Testing by hand shows this works, but we should automate it at some point.

**Comment by SamCoVT** [comment]
I like your solution for implementing a limit on negative **ALLOT**.
If you negative allot more than the dictionary (or allot more than the rest of ram) it looks like Tali prints an error message and then jumps to **ABORT**.  That's going to make automated testing difficult as it will abort the test.  We can certainly add an automated test for positive and negative small values.  I'd be happy to write the tests for that.
