### ISSUE TITLE
EVALUATE stops early or goes too far

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#130]
I'm working on getting LOAD to work and I'm having weird issues with *EVALUATE*.  When given a memory address and a length, sometimes it stops early, and sometimes it continues beyond the end of the memory described.  I suspect this is a 16-bit math issue, but I haven't found it yet.  Here is an example you can see (sorry for the 1024 character string, but it's the block I'm having issues with and this lets you have it in memory without any of the block words.)
```
s" ( Test screen for testing LOAD and THRU - screen 13 )           cr 1 .                                                          cr 2 .                                                          cr 3 .                                                          cr 4 .                                                          cr 5 .                                                          cr 6 .                                                          cr 7 .                                                          cr 8 .                                                          cr 9 .                                                                                                      cr 10 .             cr 11 .                                                         cr 12 .                                                         cr 13 .                                                         cr 14 .                                                         cr 15 .                                                         " evaluate
```
Pasting this into py65mon gives:
```
1 
2 
3 
4 
5 
6 
7 
8 
9 
10 
11  ok
```
and that's exactly what I get on my hardware as well.  It should be printing 1 through 15.  For reference, lines 0-11 are 768 bytes out of the 1024 bytes that are supposed to be processed.  Because this is exactly 256 bytes away from the real end of the string, I suspect a carry error somewhere when calculating the 16-bit length or remainder.  The data going into interpret is correct (eg it shows 1024 correctly for the length and the address is good).

For other content, the parser appears to traveling beyond the end of the string and gives an unknown word using the bytes just beyond the string in RAM.  It's worth noting that the strings I am using are mostly spaces, and the last couple of lines (64-char sections, really, as there aren't any newlines) are usually blank (filled with spaces) when it runs off the end.

**Comment by scotws** [comment]
Huh. A quick test shows that it does what is supposed to on Gforth, and I agree this looks like some 16-bit problem. Alternatively, could this be a problem with **S"** or does this occur with other stuff as well?

**Comment by SamCoVT** [comment]
It's not a problem with **S"** (at least, I don't think it is) because it also happens with blocks.  I can print them to the screen just fine, but when I try to evaluate them, I get this odd behavior.  I'm going to try to hunt this down this weekend in the debugger to see what's going on.   I'll let you know what I find.
