### ISSUE TITLE
How do I get BLK in the dictionary in assembly?

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#139]
I'm starting to look at what needs to be done to assemblerize some of the block words.  One of the things needed is the variable **BLK**.  I'd really rather not make it a zero-page variable (but that is the easiest solution,) so I was trying to figure out how to get it in the dictionary.  Right now it's in forth_words.fs, so that's the easy way to get it in the dictionary.  

If I assemblerize the the block words, or update any of the existing words that should know about **BLK** (like **EVALAUTE**), then it needs to be in the dictionary.  I understand what the code for a variable looks like, but what do I use for it's address?  I don't mind the dictionary header being in ROM, but I need the actual variable location to be in RAM and ideally in the dictionary.  How do I get it there?  Does it make sense to use a deferred word here?  

**Best thought so far:**
Do I modify **COLD** to always put it as the first word in the RAM dictionary and move cp along one cell?  That would make it so if cp0 got moved, it would follow along, and the address would always be known at compile time (as wherever the user sets cp0 to), so the assembly can just return the address of cp0.  If we need other variables like this, we can reserve them the same way.  The headers and assembly will be in ROM, but the actual data for them is stored right at the beginning of the RAM dictionary.  I don't think there are a lot of variables that need this treatment, but there may be some others (thinking of wordsets).

**Comment by SamCoVT** [comment]
I'd still like to figure this out because the wordset stuff is going to need a bunch of variables.  It makes me sad every time I steal some data stack space for a zero page variable, and I'd rather not waste that on variables like BLK and SCR that may never get used.

I just realized that I can play the `.alias` game to define where in memory they go, based on some other alias to make sure they are in RAM, and make sure cp0 is moved along to reserve the space.  Each variable I need would be based on the address of the previous one, so it's easy to add more if needed.  Then, in the assembly, I can just put the address of their RAM location on the stack using those labels.  This also allows the user to move these variables around if needed.

I don't want to put the variables in the platform files (which is where my first thought was to put these, as it's where cp0 is defined) because that would be a pain to have to update multiple files to add a variable, but perhaps we could make a single "variables.asm" or some such file that has them all in it, and then that would be included from the platform files with a `.require` line.  Using labels in the platform file, the actual location of these variables could be controlled.  I would default to putting them where cp0 is now and move cp0 along by the correct amount (perhaps by having a variables_end or some such label to denote where exactly they end).

As a bonus, because these variables would be one after another in memory, we could use **MOVE** to copy initial values from ROM into RAM at startup for all the variables created this way.

**Comment by scotws** [comment]
Then we should probably start implementing the **USER** variables, which is (if I understand this correctly) what that area is. If you look at https://www.forth.com/starting-forth/9-forth-execution/ , they put them above the buffer area; the variables they have are:

- **TIB**  Contains the address of the start of the terminal input buffer.
- **#TIB**  Contains the size of the terminal input buffer.
- **SCR**  A pointer to the current block number (set by LIST).
- **BASE**  Number conversion base.
- **CP**  Dictionary pointer. Pointer to the next available byte.
- **>IN**  A pointer to the current position in the input stream.
- **BLK**  If non-zero, a pointer to the block being interpreted by LOAD. A zero indicates interpretation from the terminal (via the input message buffer).

**TIB** and **#TIB** are our **CIB** and **CIBLEN**, which we won't need to move to USERland until we really have multitasking. Same for **BASE**, **>IN** and **CP**. **SCR** and **BLK** you've already mentioned, we'll need those. Not sure if we want a minimal move now and wait for multitasking for the rest, or if we want to move what we can to get it over with. Probably my current `editor1` to `editor3` (six bytes total) should go there as well.

I also found http://www.mosaic-industries.com/embedded-systems/legacy-products/qed2-68hc11-microcontroller/software/chapter_15_user_area_tour which *ye gods* has a lot of user variables, but some including the vocabulary that might be helpful. 

A superficial reading seems to show that there is a "user pointer" (**UP**) that, ah, points to the part in RAM where the block of these variables (the "user table") is, which also will contain a link to the next user table once multitasking is up and running. So they're using a simple linked list. As long as we're just single-tasking, we just need a `user` address on zero page to point to the beginning of the user area, and then handle it with the offset?

As for copying the initial values, if you look at **COLD**, at the moment we take the values from the `.alias` directive in the platform files and initialize them the hard way. There used to be a comment there that once we know what we were doing, the idea was to stop that foolishness and **MOVE** them from ROM in one block, just like you suggested. (Tali Forth 1 actually still has that line:
```
         ; TODO move this to a table once we know what we are doing 
```
At some point I must have deleted it from Tali 2.) I'm wondering if we can just put that table for system (zero page) and user variables in the platform files somewhere? Seems messy to have two definition files for each system ... though it doesn't really belong in the kernel. Hmm.

**Comment by scotws** [comment]
I should add that *Threaded Interpretive Languages* by Loeliger suggests a Forth word **USER** that takes a byte as the internal offset and returns the value, but that isn't standard (the book is from 1981). Gforth as far as I can tell uses `useraddr` under the hood to the same effect, but **see useraddr** tries to start some disassembler that I don't have installed and crashes on my Ubuntu 18.04, so not sure what it does. Everything being equal, I wonder if we actually need a new, non-standard word for this.

**Comment by SamCoVT** [comment]
I think I'd like to try moving BLK and SCR first and leave the rest in zero page where it currently resides.  That's the simplest way to get started on this without disturbing too much, and it will open up the path to assemblerize the block words.  

Once I get that figured out, I'll starting adding things to it.  I need to reserve the vocabulary stuff for #126 so I think that will be the next thing put in.  

For now, I think it's going to be best to leave most of the stuff currently in zero page where it is, and we can start migrating it after 1.0 when we go to add the multitasking.  I read the documentation for the qed-forth that you mentioned, and I like the idea of having a single UP (user pointer) in page 0 that points to a table of variables, and then have the words for those variables just calculate the offset from the beginning of the table.  That makes it so you only need to swap UP around to make multitasking work.

I did notice that their multitasking uses separate stacks, which means the current underflow checking might need to be made smarter (eg it will need to calculate where the stack should be instead of having it hardcoded like we currently have), but we can cross that bridge once we actively start on the multitasking.  

For now, my medium-range goal is to get enough of this working to add the vocabulary words.

**Comment by SamCoVT** [comment]
I got this working in #177, and moved BLK and SCR into the user variables, which are allocated by `COLD` right at the beginning of RAM.  Ultimately, some of the other zero-page variables will get moved into the user variables as well, but this is a good start.
