### ISSUE TITLE
Add Game of Life to User Words file once block word set  is complete

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#142]
We currently have a bunch of fun routines in `forth_code/user_words.fs` such as **MANDELBROT**. Once the block word set is fully functional, we could include Game of Life for demonstration purposes. One variant is at http://wiki.c2.com/?ForthBlocks . By default, this would be commented out.

**Comment by scotws** [comment]
So this is what I got so far -- it works fine with Gforth, and will load with Tali Forth when put in user_words.fs (where it uses all the space we have left), but something is either wrong with the `key` routine on py65 version or it is just so slow that you can see it work. I'm going to leave this for now, but at some point it would be fun as a demonstration of blocks. **WARNING:** Currently set up to load the ram disk and use blocks 1 and 2, which anybody with real hardware is going to want to change.
```
\ -------------------------------------------------------
\ GAME OF LIFE by Scot W. Stevenson <scot.stevenson@gmail.com>
\ See https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life
\ Inspired by http://wiki.c2.com/?ForthBlocks
\ First version: 21. Dez 2018
\ This version: 24. Dez 2018

\ Remove the following line if you have actual hardware with blocks. This is for
\ the py65 test version
4 block-ramdrive-init

marker life-game
true strip-underflow !

\ Cells are stars (ASCII 42), empty fields are blanks (ASCII 32)
42 constant star

\ By default, we use the blocks 1 and 2 for the game. Change these to fit your
\ storage system
variable stateblk  1 stateblk !
variable lifeblk   2 lifeblk !
variable statep      \ pointer to current cell (addr)

: wrapy  ( u -- u )
	dup 0< if drop 15 then 
	dup 15 > if drop 0 then ;

: wrapx ( u -- u )
	dup 0< if drop 63 then 
	dup 63 > if drop 0 then ;

\ Wrap around all screen edges
: wrap  ( x y -- x-n y-n )  wrapy swap  wrapx swap ;

: alive? ( x y -- f )
   wrap  
   64 *  +           ( u )       \ calculate offset
   lifeblk @  block  ( u addr )  \ get start of life block
   +                 ( addr+u )  \ calculate address of cell
   c@ bl <>
;

\ If true, save 1, if false, save 0 )
: bool>int ( f -- u )  if 1 else 0 then ; 

\ Get status of neighbors. All are ( x y -- x y n )
: (-1,-1)    2dup 1- swap 1- swap  alive? bool>int ;
: (0,-1)  >r 2dup 1-               alive? bool>int r> + ;
: (1,-1)  >r 2dup 1- swap 1+ swap  alive? bool>int r> + ;
: (-1,0)  >r 2dup    swap 1- swap  alive? bool>int r> + ;
: (1,0)   >r 2dup    swap 1+ swap  alive? bool>int r> + ;
: (-1,1)  >r 2dup 1+ swap 1- swap  alive? bool>int r> + ;
: (0,1)   >r 2dup 1+               alive? bool>int r> + ;
: (1,1)   >r      1+ swap 1+ swap  alive? bool>int r> + ;

\ Count number of neighbors
: neighbors ( x y -- n )  (-1,-1) (0,-1) (1,-1) (-1,0) (1,0) (-1,1) (0,1) (1,1) ;

\ If a living cell has two or three neighbors, it survives
: stay-alive? ( n - f )
   case
      1 of false endof  \ underpopulation
      2 of true  endof  \ just right
      3 of true  endof  \ just right
      false swap        \ all other: overpopulation
   endcase ;

\ If a dead cell has three neighbors, a new cell is born
: born? ( n -- f )  3 = ;

: lives? ( x y -- f )
   2dup neighbors    ( x y n )
   -rot              ( n x y )
      alive? if         ( n )
      stay-alive? else  ( f )
      born? then        ( f )
;

: newstate  ( -- )
   stateblk @  block   ( addr )
   update 
   statep ! ;

\ Save state, move on to next cell
: state! ( c -- )
   statep @  c!  
   1 statep +! ;

: mark-alive ( -- ) star state! ;
: mark-dead ( -- ) bl state! ;

: iterate-cell   
   2dup swap 
   lives? if mark-alive else mark-dead then ;

\ Walk through 64 columns
: iterate-row   ( -- )
   0 begin 
   dup 64 < while 
      iterate-cell 1+ repeat 
   drop ;

\ Walk through 16 lines
: iterate-block  ( -- ) 
   0 begin
   dup 16 < while     
      iterate-row 1+ repeat 
   drop ;

\ Swap life and state blocks
: generation ( -- )  lifeblk @  stateblk @  lifeblk !  stateblk ! ;
: iterate  newstate iterate-block generation ;

: done? key [char] q = ;
: prompt   cr ." press q to exit; other key to continue" ;

\ Print the current state
: view  ( -- ) 
   page  
   lifeblk @  list
   prompt ;

\ Start with some cells. Change these values to produce different starting
\ states
: newgame ( -- )
   lifeblk @  block  ( addr )
   dup 10 +  ( addr+10 )  star swap !
   dup 11 +  ( addr+11 )  star swap !
   dup 12 +  ( addr+12 )  star swap !
       13 +  ( addr+13 )  star swap !
   update
;

: life  
   newgame
  	begin  
      view iterate  
   done? until
   
   false strip-underflow !
;
```

**Comment by SamCoVT** [comment]
I haven't been able to get this to work either.  It's ridiculously slow in py65mon because it goes back and forth between blocks, and Tali only has the one buffer.  It could be much faster if it were to "render" into a separate 1K buffer and then copy that back into the block buffer.

I thought it needed some initial "stuff" to start working, so I put some stars in both blocks, but I still couldn't get it to do anything and I gave up.  After reading this code again, I'm convinced that this code expects two simultaneous block buffers and we just don't have that.  It uses a pointer to fill in the "stateblk" while it looks at the data in the "lifeblk".

Now that I see the problem, I can probably rewrite this so that it works, and it should be way faster as well.

**Comment by scotws** [comment]
Right. Note that `generation` swaps the two blocks as part of iteration. 

The original code was totally sans comments and seemed to expect that you'd edit in the starting stars by hand. I added "newgame" -- this is all on Gforth, which saves blocks to a file -- for that and that's when I got it to work at all. I think there is a lot of stuff that can be improved: The `(1, 1)` looks like it might be a candidate for `create / does>`, and `64 *` would obviously be more happy as a bunch of left shifts. I was just happy to get it working.

I'll turn it over to you for now. I had just stumbled across it and though it would be a good demonstration of how blocks can be used for stuff.

**Comment by scotws** [comment]
Hmm. Thanks for this - though the whole idea was to have something that showed how cool blocks and buffers could be. Given how slow this is, it might have the reverse effect :-). 

I suggest we leave it for now - I can close it, but we can always find it again later here if we are inspired. Again, thanks. Didn't turn out as I had hoped.
