### ISSUE TITLE
LOAD needs to be redone (they way I did it the first time was correct, of course)

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#144]
My reading of the current ANS standard seems to indicate that LOAD should evaluate the entire block (as if it was a single input buffer).  My original code did it that way, but I had a problem when I had a line with 64 characters in it, and Tali thought it was "touching" the beginning of the next line, combining two lines (because there aren't actually any newlines in the block.)  Here's an example:
```
: aword ( 64 char long line )                                   ;
: bword ( stuff here ) ;
```

If you evaluate the block as a single input buffer, then the forth interpreter gets the following words (ignoring the comments above):
```
: aword ;: bword ;
```

where the ;: is the end of one line connected directly to the beginning of the next.  Forth treats this as a single word, and this one causes an undefined word error.  I tried this on gforth, and that's exactly what I got for an error.

I changed load to use a loop to evaluate each line, in order.  This fixes the "problem" and has the nice side benefit of making the comment word \ work without any extra work, but now that I'm re-reading the standard, I think I need to evaluate the whole buffer in it's entirety instead.  I looked at some other forths, and most of them seem to have made the same decision I made and do things line-by-line, but gforth's behavior seems to agree with the ANS standard that it should be done as one 1K chunk.

If I fix this, it will mean that programmers should probably not put more than 63 chars on a line, especially if the next line doesn't start with a space.  It will also break the \\ word, as that will comment out the rest of the block (until it gets rewritten to know about blocks.)  The \\ word is optional, so I can fix that at a later date.

**Comment by scotws** [comment]
See, this is one of the things I'd never thought of, because I automatically assumed it would be line-by-line. However, I agree, it seems like the whole block is evaluated. The _Forth Programmer's Handbook_ 3rd editon (Conklin & Rather) has this to say (p. 249):

> When **LOAD** is encountered, interpretation of text from the current input source is suspended and input is taken from the specified block. The text interpreter starts at the beginning and processes each word until it reaches the end of the block (after 1024 characters).


A bit later:

> The process of **LOAD**ing disk blocks is identical to processing the same information entered at the terminal or loaded from a text file, but all information in a single block is processed as a single string (i.e., there will be no embedded carriage returns).

I just realized there is also a style guide for blocks in Appendix C. I guess that's what I'll be reading on the train on the way to work later :-).
