### ISSUE TITLE
Add list of 65c02 hardware projects that Tali has been ported to

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#154]
I'd like to add a section to the Manual with links to projects that Tali has been ported to (I dimly remember having put in the commented-out version of the headline already somewhere). Not everybody is going to want to do this, so it will be strictly optional with permission given, and a statement of how they want their names. But I think that would be a nice showcase.

@SamCoVT , if you want to be included, is there a link for a website or Forum page somewhere? And with which name? I've asked the Steckschwein crew via 6502.org forum PM.

**Comment by SamCoVT** [comment]
Can you open this one up again and assign it to me?  I haven't gotten around to putting my files anywhere internet accessible yet - perhaps I'll just put my files up on github and I can link to it there.  I'll add my system once I've done that.

**Comment by SamCoVT** [comment]
I guess you don't need to reopen this - I just issued a pull request #158 that has this in it.
