### ISSUE TITLE
Consider moving from SM/REM to FM/MOD as defaut

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#155]
Tali currently uses **SM/REM** as the default division word, whereas the reference implementation Gforth uses **FM/MOD** (see results of **s" floored" environment?**). We should probably switch to follow Gforth, unless somebody knows of a good reason not to?

**Comment by SamCoVT** [comment]
I have no issues with this.  The standard allows either.  If you want to have the same behavior as Gforth (to make testing expected behavior easier, and I did just read that Tali follows Gforth in the Tali docs somewhere,) that seems like a good enough reason to make the switch.

**Comment by SamCoVT** [comment]
Did you see [the recent 6502.org forum post](http://forum.6502.org/viewtopic.php?p=63947#p63947) on this very topic?  Apparently Gforth has different behavior depending on the platform.  That's an argument for just leaving it alone, however I don't see a problem with changing it if you'd like it to match what your desktop does (at least, until you replace your desktop with a different architecture CPU.)

**Comment by scotws** [comment]
Yeah, I read that. We just leave it as it is then, because It Works (TM).
