### ISSUE TITLE
Add further commands to ed

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#162]
First in line are **#c+-;**, then **efjmrs**, possibly then **!** if we can figure out how to work it with the stack. Actual work on these words will be of lower priority until we have a testing routine to catch errors, see #159 for details.

**Comment by scotws** [comment]
After dogfooding **ed** for a bit, I'm going to change the stack words so that `( -- addr u )` gives you the block where the text is stored at the end. That just makes the workflow that much easier.

**Comment by scotws** [comment]
This is going to take a while longer, because I'm going to have to rewrite the way **ed** deals with cases where no parameter was given. Thought I could get away with using the parameters to signal that, but that turns out to be horrible, so I'll need real flag bits. Sigh.

**Comment by scotws** [comment]
@SamCoVT The new **S\"** made an enormous difference for testing **ed**, good idea to do that now!

**Comment by SamCoVT** [comment]
I had wanted add **S\\"** for a while - I wanted quotes in strings and thought you would need newlines in strings, so it made sense to do it now.  I'm glad it's working for you.

I took a quick peek at your ed.fs tests to see it in use - there's a TODO at the top that you can get rid of now :)

**Comment by scotws** [comment]
I'm putting this on hold because of space considerations and until I have a better feeling for what words are even needed. `s` would be cool, of course, but that's going to be hellishly long in 8-bit assembler. 

I've also included a few lines in the documentation about how to completely remove `ed` from the build for those people who know they won't be using it. That saves 2K.

**Comment by scotws** [comment]
I'm going to close this for the moment until we decide that we want to open more ROM (if ever). For small things, the current command set is fine.
