### ISSUE TITLE
Edit: input and ouput routines need to save tmp variables if they touch them

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#163]
Because the output routine is a vector, and because it could technically be redirected to a word written in Forth that uses the TMP1 variable, TYPE should push/pop TMP1 around the jsr to emit_a (which then jumps to the (output) vector.  I can do this one.

It may also be worth noting how to get A onto the stack for those wanting to write their own output routines in Forth, but I think that should wait until we have an assembler.

**Comment by scotws** [comment]
Thanks for this. The whole `tmp` variable setup is asking for trouble with increasing complexity, but it seems to mostly work, and pushing stuff to the stack every time is just so expensive for the cycle count.

Agree with the A-to-stack thing. Maybe we could just shove it in some corner of the documentation for now? I think I have finally figured out how to use one set of mnemonic data for both assembler and disassembler without using too much space, but it will take me a bit to get it all set up.

**Comment by SamCoVT** [comment]
Sounds good - I'd love to see an assembler.  Once this is fixed up, I'll see about adding some documentation on I/O redirection.

**Comment by SamCoVT** [comment]
I think we are approaching the point where it is fine to use the `tmp` variables in your word, but you should save/restore them before/after you call any other words unless you verify that those words don't use them.  In the case of `emit`, we have a replaceable vector, so we can't make that guarantee.  It looks like `key` doesn't use the `tmp` variables at all, so we should be safe there.

**Comment by SamCoVT** [comment]
OK...  so this is a bigger mess than I initially thought.  I updated **ACCEPT** and **TYPE**, but then did a grep to find other uses of emit_a and I was sad...
```
[scolwell@orion TaliForth2]$ grep -n 'key_a\|emit_a' *.asm                                  
ed.asm:585:                jsr emit_a
ed.asm:597:                jsr emit_a
ed.asm:607:                jsr emit_a
ed.asm:613:                jsr emit_a
ed.asm:1123:                jsr emit_a
ed.asm:1283:                jsr emit_a
native_words.asm:410:                jsr key_a
native_words.asm:445:                jsr emit_a
native_words.asm:467:                jsr emit_a
native_words.asm:472:                jsr emit_a
native_words.asm:474:                jsr emit_a
native_words.asm:476:                jsr emit_a
native_words.asm:557:                jsr emit_a
native_words.asm:562:                jsr emit_a
native_words.asm:567:                jsr emit_a
native_words.asm:585:                jsr emit_a
native_words.asm:601:                jsr emit_a
native_words.asm:904:                jsr emit_a
native_words.asm:906:                jsr emit_a
native_words.asm:909:                jsr emit_a
native_words.asm:912:                jsr emit_a
native_words.asm:963:                jsr emit_a
native_words.asm:2008:                jsr emit_a
native_words.asm:2850:                jsr emit_a
native_words.asm:2867:                jsr emit_a
native_words.asm:2869:                jsr emit_a
native_words.asm:3037:                jsr emit_a
native_words.asm:3100:emit_a:
native_words.asm:3102:        ; around with the Data Stack. This is emit_a's job, which still                                                                                          
native_words.asm:4225:                jsr key_a               ; returns char in A
native_words.asm:4234:key_a:
native_words.asm:5280:                jsr emit_a
native_words.asm:5283:                jsr emit_a
native_words.asm:5593:                jsr emit_a
native_words.asm:5595:                jsr emit_a
native_words.asm:5597:                jsr emit_a
native_words.asm:5599:                jsr emit_a
native_words.asm:7265:                jsr emit_a
native_words.asm:7296:                jsr emit_a
native_words.asm:7308:                jsr emit_a
native_words.asm:7317:                jsr emit_a 
native_words.asm:8375:                jsr emit_a      ; avoids stack foolery
native_words.asm:8419:                jsr emit_a
native_words.asm:8868:                jsr emit_a
taliforth.asm:241:*               jmp emit_a
taliforth.asm:524:                jsr emit_a
taliforth.asm:538:                jsr emit_a              ; allows vectoring via OUTPUT
```
Line numbers may be different as I've already been editing.
`key_a` isn't bad as I already have the places that's used (**ACCEPT** and **KEY**), but the rest is a mess.

Because of the way that emit_a words, I can't even save all three temps in that word because it technically never returns.  I'd have to add another jsr level, and that's just ridiculous.

### New Solution:  
A new input or output routine may use the temp variables, but must save/restore them if it touches them.  If using forth to code these, the programmer is responsible for checking the words used and should probably stick to simple words.  

That allows us the rampant use of emit_a without having to do a save/restore every time.  I've already handled this in the code I gave you for redirecting to a string by not using the **+!** word.  

My new task is to update the documentation instead to inform the users of this.

**Comment by scotws** [comment]
The think about `emit_a` is that it is so incredibly useful for testing 
```
lda #'q
jsr emit_a
```
is basically the first thing I do to see if a certain part of the code is even used. I think that few people are going to be revectoring the input or output routine on the fly, so I like your solution of making anybody who does make sure they're doing the right thing. 

Still, the whole `tmp` situation is a mess, but I can't really think of a better solution at the moment. If this were the 65816, you could just say, fine, we'll put it on the stack, because you can move the stack around and access stuff with the `lda 1,s` instructions (it's really, really hard to go back to the 65c02 after the 65816). I've also been looking at the RISC-V a lot - when it comes out in affordable silicon, I'll probably be getting a SBC of some sort - and they have this nice system of registers used for various call levels. They also have 32 registers :-).
