### ISSUE TITLE
Updates to the docs.

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#168]
I'm doing a read-through of the current documentation.  This is just a list of items/locations in the manual that need updating because of changes we have recently made and a few straggling typos.  I plan to go back through and fix them all at once.

File | Change to be made
---- | --------------------
ch_why.adoc | Forth(((Forth)) has unbalanced parens causing one to show up on the docs.
ch_why.adoc | "why got to" --> "why go to"
ch_why.adoc | "commented. And" --> ???  Period to comma?  Remove and?
ch_overview | "most attractive solution" --> spell out that it was actually the selected solution as well.
ch_installing | "sudo pip install -U py65" --> consider providing the --user option instead of using sudo
ch_installing | "The Platform Files" --> add make command to make .bin file for new user platform file.
ch_running.adoc | the word list
ch_running.adoc | Tali-specific words - add ALLOW-NATIVE
ch_running.adoc | "To complete turn off" --> "To completely turn off"
ch_internals.adoc | Input section says Tali doesn't currently support blocks
ch_internals.adoc | Mention that "keyboard" can be redirected using INPUT vector
ch_internals.adoc | Add ALLOW-NATIVE option to Enabling Native Compiling on New Words
ch_internals.adoc | "This is Good Thing" --> "This is a Good Thing"
ch_internals.adoc | move: has a backtick on one side and a colon on the other.  Should be backticks.
ch_developing.adoc | "and the make" --> "and they make"
ch_developing.adoc | "Naively" --> "Natively"
ch_developing.adoc | "kernel_getc" (two places) - change to "key_a" for redirection to work.
ch_developing.adoc | "kernel_putc" (two places) - change to "emit_a" for redirection to work.

**Comment by scotws** [comment]
Thanks for this, it's a rather horrible job, I'm afraid. I keep trying to remember to at least run `aspell` over things ... I noticed that the PDF version of the docs is now at 66 pages. Yikes.

**Comment by scotws** [comment]
@SamCoVT  FYI I've included an experimental conversion method to get us to markdown, though there are still some problems like the title being eaten. Also, the `(((index)))` index elements aren't handled correctly. The basic text is there, though, so we now have something to tweak.

It will probably make more sense to rewrite the chapters with `=` (level zero) headings and then level them up in the main file, but that's other tweaking for later.

**Comment by SamCoVT** [comment]
Sounds good.  Once I have some more brain power, I'll finish the readthrough and then go back and fix up all of the little details at once.  It's pretty well written (and one of the things that attracted me to try it on my single board computer), and these are really just a very small percentage of the overall document.   One other thing I see as I read is that there could be some more cross-referencing.  We now have entire chapters for things that are briefly mentioned elsewhere in the document.   

I think it's the teacher in me that just wants to go through and fix all of the little errors.

**Comment by SamCoVT** [comment]
I haven't really found any favorite mistakes of yours.  Truth be told, I found the docs to have a pretty low error rate overall.  A lot of these were misspellings that spelled another word, thus they were not caught by aspell.  Some of it is also just old information, and Tali 2 has grown up quite a bit since it was written.
