### ISSUE TITLE
There is no warning when redefining variables or constants

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#176]
Should there be?  We currently warn for redefining words (since #13), but not if you make a variable or constant using an existing name.  Gforth warns in both of these cases.

**Comment by SamCoVT** [comment]
It looks like moving the check from `;` to `CREATE` would cover all of the bases.
In `CREATE`, after calling parse_name (and checking for a zero length string), the address and length of the name are on the stack.  Something like: `2dup find-name if <print redefinition message here> then` (but in assembly, of course) might do it.

I believe this will be compatible with the trickery that `:` does in order to hide the new word until it is done, and will make `:`, `VARIABLE`, `2VARIABLE`, `CONSTANT`, `DEFER`, `MARKER` and `VALUE` all have the same behavior.  Gforth warns on all of these words.  The only behavior that would be different from Gforth's (and Tali's current behavior) is that Gforth (and the current version of Tali) waits until the `;` to issue the message for a multi-line word definition.  eg:
```
( Showing input and response )

( Gforth and Tali now )
: aword  compiled
; redefined aword   ok

( Proposed Tali change )
: aword  redefined aword compiled
; ok
```
If you want Gforth's behavior, I can make it happen, but it's more complicated.  This isn't a critical issue, so a decision can wait until you have time to consider it.

**Comment by scotws** [comment]
I think it would probably be best to follow Gforth here, since it is something of the de fact standard for Forth at the moment. Since you already know what to do, I'll assign this to you for whenever?

**Comment by SamCoVT** [comment]
I'll look into it.  It's complicated by the fact that users can use the word CREATE in their own words, and the fact that `:` needs to tell `CREATE` not to check the name, and also tell `;` that is should check the name, but only if the word wasn't created with `:NONAME`.  For the variables and constants etc., however, it should be `CREATE` that does the check.  It should be good fun...

**Comment by SamCoVT** [comment]
I did use bit 7, but ended up inverting its use to mean "Don't print the message".  That way, it only needs to be touched by `:` and `;` and none of the other words have to know about it.  This also allows for correct behavior with defining words made by the user with `CREATE` in them.  The default behavior is to print the message right away.

**Comment by scotws** [comment]
I'm never sure about this instruction, but shouldn't we be able to convert the sequences
```
  lda #$80
  ora status
  sta status
```
to something like this?
```
  lda #$80
  tsb status
```
I don't think we care about the Zero Flag in these cases. I think then later we can make
```
lda #$7F                ; Clear bit 0 of status to indicate new word.
and status
sta status
```
into 
```
lda #$80
trb status
``` 
as well. I see what you mean with the cycle count going through the ceiling, on the other hand, I think it is very much worth it to have these warnings, especially for people new to Forth.
