### ISSUE TITLE
CLEAVE doesn't work with multiple delimiters or leading delimiter

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#201]
See source code for details. This might require a deeper rewrite, for now it is listed in the manual as a **known issue**. Tests for the correct behavior ("aaa   bbb" and " aaa bbb") are partially included.

**Comment by SamCoVT** [comment]
Is the comment at the top of CLEAVE, saying that PARSE and PARSE-NAME use it, historical or future looking?  I only found hexstore using it.

If it's historical, CLEAVE looks an awful lot like parse-name.  Would it be possible to write cleave to save and replace cib,  ciblen, and toin - then run parse-name - then turn the results into what cleave needs and restore cib/ciblen/toin?  That would provide identical behavior to parse name and be smaller (I think) with a slight reduction in speed due to pushing/popping cib, ciblen, and toin.

**Comment by scotws** [comment]
Basically, I didn't think **cleave** through in great enough detail, it was something that came up while working on **hexstore**, and yes, there is rather large overlap with **parse**. What we need is a version of parse that works with **( addr u c )** instead of **( "name" c)**, or, as you say, redefine the input buffer for the duration while making sure we don't violate (https://forth-standard.org/standard/usage):

>A program shall not write into the input buffer. 

which would be the easy way out. So this shouldn't be a biggy, it is just me not leaping before looking.

**Comment by scotws** [comment]
So there is **save-input** and **restore-input** (https://forth-standard.org/standard/core/SAVE-INPUT) for just these situations. The problem is that they push everything to the Data Stack, which means you need **n>r** or other means to get them out of the way if you need stuff on the Data Stack. We want it on the Return Stack.

We've already solved this problem in **evaluate** in a brute-force way, where we LDA / PHA our way through  `cib, ciblen, toin` and `source-id` - eight bytes which require three instruction bytes each for a total of 24 bytes each way (I don't even want to think about cycles). That might be worth turning into some loop construct regardless of **cleave**, as long as these four variables come right after another in the Zero Page. 

Anyway, we could create two words - say **input>r** and **r>input** -- to isolate that part and reuse it with **cleave** probably by way of **execute-parsing**. It will still be a lot of moving bytes from A to B, but we should be able to reuse a lot. I'll look into it after we've assemblerized some more and I've rewritten the underflow checks.

**Comment by SamCoVT** [comment]
I like the idea of 'input>r' and 'r>input' and then implementing `execute-parsing` using those.  They will be usable in `evaluate` as well, and that will help to reduce duplicate code.  I agree that we can leave this for now, as it currently only affects hexstore.

**Comment by scotws** [comment]
I now have `input>r` and `r>input` up and running with `evaluate`, so there is the first step. Now to figure out `execute-parsing`, which might take a little longer.
