### ISSUE TITLE
Make sure C, doesn't allocate more memory than we have

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#218]
`c,` currently does not check if we're out of RAM, which is not really a problem for the default py65 setup but might be bad on systems with less memory.

**Comment by scotws** [comment]
It turns out that `,` (COMMA) has the same problem. We can use the routine we have in `allot` as a subroutine for all three cases.

**Comment by SamCoVT** [comment]
I think it makes sense for `allot`, where you can easily run into trouble, but perhaps not so much on the words that are allocating 1-3 bytes at a time.

**Comment by scotws** [comment]
Yeah, I think we'll just leave it as it is.
