### ISSUE TITLE
Replace BRANCH/0BRANCH by CS-PICK/CS-ROLL?

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#23]
0BRANCH and BRANCH are holdovers from Tali Forth 1's basis on FIG Forth, most modern ANSI Forths use CS-PICK and CS-ROLL. It would probably make more sense to switch as well.

**Comment by SamCoVT** [comment]
We don't have a separate control stack, which is where those words would be useful.  Would there be any benefits to switching?

**Comment by scotws** [comment]
No benefits, this works and is tested. I'm closing this until somebody finds a good reason to rewrite a whole lot of code for no obvious benefit.
