### ISSUE TITLE
User's output routine must leave char in A

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#249]
The output routine is expected to leave the character in A when it returns.  In particular, the `spaces` word only loads A once and then calls the output routine over and over to print the correct number of spaces.  I'll add some documentation in the both the platform file and the manual mentioning this.  
As an alternative, we could investigate if `spaces` is the only affected word and rewrite it (it just needs to load a space into A before calling the output routine).  I like this option better as it makes it easier for new users to write their I/O routines.  I'll investigate and see what the best option is.

**Comment by scotws** [comment]
Thank you!
