### ISSUE TITLE
Updates to instructions in docs/ch_developing.tex

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#26]
In docs/ch_developing.tex, starting on line 37 are instructions for cloning and installing Ophis.  I believe the cd command on line 38 is incorrect.  It currently says:

```
git clone https://github.com/michaelcmartin/Ophis
cd src
sudo python setup.py install
```
but on my Fedora system it needed to be:

```
git clone https://github.com/michaelcmartin/Ophis
cd Ophis/src
sudo python setup.py install
```
as the git clone command created an Ophis directory with the src directory inside of that.

Starting on line 42 are instructions for assembling Tali, however they reference an assemble.sh script that doesn't seem to be in the repository.  I did find a Makefile, which seems to work fine.  I believe this is just out of date, as I have seen you mention a Makefile somewhere else (might have been on 6502.org)

I'm going to try to get Tali running on my homebrew 65C02 SBC, so I'll let you know if I find anything else.  So far, everything has been documented very well.

**Comment by scotws** [comment]
I can confirm the problem -- @rwiker contributed a real make file, and I haven't updated the documentation.
