### ISSUE TITLE
Makefile needs to be updated for .PRG output (eg. 24K images)

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#261]
The *.prg target in the Makefile still has ophis as the command, but ophis can't compile this source code anymore.  The command will need to be changed over to 64tass with the correct options to make a 24K (or smaller) image that can be copied into RAM and run.  .PRG files have a two-byte header that says where to start copying it to and then the data..

**Comment by SamCoVT** [comment]
Solved by #263

**Comment by scotws** [comment]
Thanks for that. No way I can test it either, but I'm sure we'll hear from the Steckschweiners if it doesn't work at some point ...
