### ISSUE TITLE
All assembler mnemonics need to be marked NN

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#268]
All of the assembler mnemonics need to be marked Never Native so that when they are used with `POSTPONE` they will be properly compiled as a JSR and not just copies of the opcodes (which include a BRA or JMP to the `asm_common:` code that is not within the xt_ and z_ labels).  This normally isn't an issue because all of these words are IMMEDIATE, however it becomes a problem with `postpone` which will compile an immediate word and it's trying to natively compile these words.

I think `push-a`, `<J`, and `<B` would be OK not being flagged as NN, but I think I'll recommend flagging at least `push-a` as NN because it seems silly to natively compile the routine that copies bytes to natively compile the push-a code.  May as well just put a JSR in there if it were to be used with`postpone`.

I've done a quick check and adding NN to the assembler words appears to resolve this issue.

**Comment by scotws** [comment]
Thanks! Hope to be at least a bit more present now ... weird times.
