### ISSUE TITLE
Some words have been tested

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#28]
I've tested the following words (using the NAME from WORDLIST.md):
```
COUNT
D_MINUS
D_PLUS
D_TO_S
DABS
DEFER
DIGIT_QUESTION
```
Should I update the magical comment line in native_words.asm and then generate a pull request?

I've also been keeping a lot of expected responses vs actual responses.  Would you like those put somewhere?  I saw you had some of your test cases in docs/ch_tests.tex - should I add the test cases to that?  My text file of tests/results is currently 160 lines long for testing just the above words.  I'm currently copying/pasting directly into a minicom session to have my hardware run the test and then copying the results back into my file for a record.

Here's an example for COUNT.  I tried not use use any words that weren't tested already, so some of this is a little brutish (eg. poking bytes directly into memory):
```
( COUNT )
( Helper definitions )
: makebuffer ( n -- ) ( -- a ) create allot ;
: addchar ( addr ch -- [addr+1] )
    over c! 1+ ;

( Create a buffer to make a counted string in. )
256 makebuffer my_counted_string

( Put a small string there. )
my_counted_string
5   addchar  ( Length of 5 )
72  addchar ( H )
101 addchar ( e )
108 addchar ( l )
108 addchar ( l )
111 addchar ( o )
drop ( drop the address )

( Testing COUNT )
my_counted_string count . my_counted_string - .
( expecting 5 1 )
( RESULTS:  5 1 )

( Put a pretend large string there )
255 my_counted_string c! ( adjust size of string )
my_counted_string count . my_counted_string - .
( expecting 255 1 )
( RESULTS:  255 1 )

( Put an empty string there )
0 my_counted_string c! ( adjust size of string )
my_counted_string count . my_counted_string - .
( expecting 0 1 )
( RESULTS:  0 1 )

```

**Comment by scotws** [comment]
First, thanks for all the help! 

For the tested words, a pull request would definitely be the easiest way to incorporate the magic words.

As for the actual testing, I can't help thinking that there has to be an automatic way -- I've been having regression problems after some of the changes, and going back and doing everything by hand is too time consuming even with cut & paste. There has to be a way to redirect the input through, say, a Python script, catch the output and compare it to a template. That would involve starting the program -- py65mon and/or minicom -- from the script as well. But this can't be a new problem. 

In the meantime, we should definitely save your work somewhere. How about a PR for a new folder "tests" and keep the text file there for the moment? Maybe with one or two lines of intro what this is all about.

Thanks again!
