### ISSUE TITLE
2/ is missing

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#31]
In working towards the goal of an automated test suite, I'm trying to get John Hayes' test software working.  It uses your forth to test your forth.  I'm off to a good start, but noticed that 2/ appears to be missing.  Here is a bit from the automated test showing 2* passing and then 2/ failing:

```
0  constant 0s  ok
0 invert constant 1s  ok

{ 0s 2* -> 0s }  ok
{ 1 2* -> 2 }  ok
{ 4000 2* -> 8000 }  ok
{ 1s 2* 1 xor -> 1s }  ok
{ msb 2* -> 0s }  ok
  ok
{ 0s 2/ -> 0s } >/< Undefined word
{ 1 2/ -> 0 } >/< Undefined word
{ 4000 2/ -> 2000 } >/< Undefined word
{ 1s 2/ -> 1s }    \ msb propogated >/< Undefined word
{ 1s 1 xor 2/ -> 1s } >/< Undefined word
{ msb 2/ msb and -> msb } >/< Undefined word
```
For reference, the word `{` doesn't do anything (just looks nice), the word `->` saves a snapshot of the stack, and the word `}` compares the current stack to the snapshot.  You essentially just put `{`, your test, then `->` and then the expected answer and then `}` and if all is well you get `ok`, but if there are problems you get an error message.

It's interesting that only the / part is undefined (eg. the 2 is missing), according to the error message.

**Comment by scotws** [comment]
Ah, cool -- this would be http://www.forth200x.org/documents/html/testsuite.html ?
