### ISSUE TITLE
Add ENVIRONMENT? as CORE word

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#36]
See http://lars.nocrew.org/dpans/dpans6.htm#6.1.1345 for details on **ENVIRONMENT?** and http://lars.nocrew.org/dpans/dpans3.htm#3.2.6 for a list of what the results should be. This is a required ANSI core word. The _Forth Programmer's Handbook_, 3rd edition by Conklin and Rather discusses this on p. 120. -- This doesn't make much sense to add until the rest of the code is stable.

**Comment by SamCoVT** [comment]
This shouldn't be too hard to do as a high level word once COMPARE is available (#45).

**Comment by SamCoVT** [comment]
COMPARE is now available.  I will give this a go, as it looks like a CASE with several COMPAREs should do the trick.
