### ISSUE TITLE
Words after a ?do ... loop don't run if the ?do ... loop never runs.

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#38]
In the following code, when actual-depth has a value of 0, I'm expecting to see `ACTUAL RESULT: { }` but instead I get only `ACTUAL RESULT: {` and the closing curly brace doesn't print.  The closing curly brace *does* print for actual-depth values 1 or more.

```
\ Added by SamCo 2018-05 to show actual results of previous test.
: show-results \ ( -- ) Print the previous test's actual results.
   s"  ACTUAL RESULT: { " type
   actual-depth @ 0 ?do
      actual-results 
      actual-depth @ i - 1- \ Print them in reverse order to match test.             
      cells + @ .
   loop
   s" }" type ;
```
Example output (when run with a test program that calls this word upon encountering an error):
```
{ 1 2 -> 3 4 } INCORRECT RESULT: { 1 2 -> 3 4 } ACTUAL RESULT: { 1 2 } ok                 
{ -> 3 4 } WRONG NUMBER OF RESULTS: { -> 3 4 } ACTUAL RESULT: {  ok                       
```
A simple stand-alone test that can be run without the test program:
```
: stuff 0 ?do i . loop 12345 . ;  ok                                                      
1 stuff 0 12345  ok                                                                       
0 stuff  ok                                                                               
```

It's possible I'm making a Forth mistake or not fully understanding all of the words I am using, so if a correction is needed, it will also need to be applied to the pull request I recently made adding this code to the tester.

**Comment by SamCoVT** [comment]
I'm trying to understand this bug, but I don't have a super clear picture of how do ... loop works.  

It looks like your version copies a chunk of assembly directly into the dictionary (rather than jsr this and jsr that) to actually perform the work needed to make do and ?do work, and it looks like ?do has its own version of this assembly (which makes sense to me so far.)

### Original Flawed Understanding
I believe the issue is that the current code uses an rts at the end of question_do_runtime (line 2363 in native_words.asm).  In my current understanding, this rts will end the currently-being-compiled word because we never jsr'd into another word.

What _should_ happen is a jump to some later point in this same dictionary definition where the word LOOP (or +LOOP) shows up, but that location isn't available yet, so some assembly-fu will be required to make it work.  The reference to LDA/PHA and dummy bytes back up in the do_common code sounds like such assembly-fu.  Perhaps a push-push-rts is used as a jump?

### New Understanding
I've read your loops.txt from Tali1 (still referenced in the assembly for Tali2, and I believe still relevant.)

It looks like question_do_runtime is trying to do the right thing.  The address of the top of the loop and the address of the end of the loop should be on the RETURN stack.  I had originally missed the fact that these were held on the RETURN stack.  You do two PLA instructions to remove the address of the top of the loop, and then use RTS to jump to the address of the end of the loop.

### Conclusion
It looks like this will take some time in the simulator tracing step by step to figure out.  It's quite mind-bending (in a good way) because some of the code is being run during compilation (when forward addresses are not known yet), but some of the code runs at runtime (where the forward addresses have already sneakily been filled in by the compile-time code run at the end of the loop).  If/when I have some free time, I may check this out in the simulator, but I don't think I know enough yet to figure out the bug.

**Comment by SamCoVT** [comment]
I believe the runtime for ?do was pulling off the return stack the very address it should be going to when it discovers the start/end values are equal.  I've commented out the two PLA instructions and it seems to be working now. See #41 for my solution.

**Comment by scotws** [comment]
I can confirm the bug, and that it was already present in Tali Forth 1 (always depressing). Running your test snippet in Gforth produces the correct behavior. Will try to get to the fix later on, thx!

**Comment by scotws** [comment]
You fix, ah, seems to have fixed it. Thanks!
