### ISSUE TITLE
Forth built-in words should be uppercase

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#48]
While poking around forth-standard.org looking at the whitespace issue, I noticed the last line of section 3.4.2 (Finding definition names) at http://forth-standard.org/standard/usage

After saying that forths can be case sensitive, it says:
`A system shall be capable of finding the definition names defined by this standard when they are spelled with upper-case letters. `

I see you already have a note on the fact that all of Tali's built-in words are lowercase in 4.2 of manual.pdf, and perhaps that is enough.  I don't really have a preference, although I have had to lowercase a lot of existing forth code to get it to work on Tali.

**Comment by scotws** [comment]
Argh, I had missed that part. What is it with Forth and upper case? Okay, if it is in the standard, it should go in Tali. But I don't have to like it. I guess it is simple enough to add. 

Suggested procedure: We run through the Dictionary the way we do now. Then, if we haven't found a word, we check to see if the first character of the word is upper case. If yes, we convert the word to lower case and run the check again. This will also mean that users can define new words in lower case, but they will be found in upper case. It will also mean a significant speed penalty for upper case words, but we can put that in the docs. 

An alternative would be to add upper case versions of the core words to the Dictionary, which would take care of user-defined words being triggered in upper case when they are defined in lower case. But that would eat a lot of memory, and we'd have to define synonyms for the the high-level Forth words, so I'd prefer the first variant.

**Comment by SamCoVT** [comment]
I suppose you have to consider Forth's age.  When I was a kid, we got a Language Card for the family Apple ][+ computer which added 16K of RAM (to the existing 48K) and the ability to display lowercase letters!

Your suggestion seems pretty reasonable, but it will need to be slightly smarter (or perhaps dumber) as not all words begin with a letter (/MOD for example.)  I don't think it's worth the effort to see if all of the letters in a word are uppercase (smarter), but it might be OK to simply lowercase a non-found word and to do a second dictionary scan (dumber, as it will find /mod for /mOd.)

**Comment by scotws** [comment]
Yes, your version makes more sense -- that way, the user can still define mixed-case words, and they will be found during the first pass, and then we just throw up our hands and try to find it in upper case.

**Comment by SamCoVT** [comment]
I think I'd like to try tackling this one.  I see you already put a note in the documentation about it, and I'll update that too.

**Comment by SamCoVT** [comment]
OK...  so I wrote it, it passes the test suite, but I don't really like it.  If you want to play with it, you can find it at https://github.com/SamCoVT/TaliForth2/tree/feature/recognize_ucase_words 

Let me see if I can enumerate what I don't like and perhaps you can make some suggestions:

The current code will try lowercasing any word that has at least 1 uppercase letter.  That way it won't do multiple scans for something like "~", and it also knows when to stop checking because, on a second pass, the word will no longer have any uppercase letters in it.  Here's a sample run.

```
Type 'bye' to exit
  ok  
5 DUP  ok
.s <2> 5 5  ok
3 dUp .s <4> 5 5 3 3  ok
: dUp +1 ; >+1< Undefined word
: dUp 1+ ;  ok
7 dUp .s <1> 8  ok
7 DUp .s <3> 8 7 7  ok
dUp .s <3> 8 7 8  ok
asdf >asdf< Undefined word
ASDF >asdf< Undefined word
AsDf >asdf< Undefined word
```
Because the string is lowercased in place, the error message "Undefined word" always shows the lowercase version.  I'd rather it had the original version, as I really don't think FIND-NAME should be modifying the string it's looking at.  

I just realized that this won't work if FIND-NAME is called on a string in ROM.  I know that forth_words.fs and user_words.fs are added into the ROM as a string - It looks like they are interpreted directly from ROM.  Regardless, I think this SHOULD work if called on a string in ROM.  
I believe if a user of Tali put an uppercase word into the ROM high level words, Tali would enter an infinite loop (at least on real hardware) because the writes used to lowercase would be ignored by the ROM and Tali would keep trying to lowercase it every time it failed to find it.
## Possible solution 1:
My preferred solution would be to lowercase the word _somewhere else_, meaning we'd need ~~32~~ 255 (I just checked ch_internals.adoc and it says Tali allows names up to 255 bytes!???) bytes somewhere else of temporary storage that is easy to access.  If I had that, I would lowercase the word over into the temporary location, adjust the appropriate tmp pointers to point to that temporary location (the size still works, so we don't need a copy of that) and then jump back into the search code.  That way, if the word is still not found, the original word is printed to the output in the error message.

Barring that, I think the decision on when to lowercase could be made smarter (eg lowercasing only when a word contains at least one upercase and no lowercase letters) with some work.  The ROM issue still remains.

## Possible solution 2:
Add NTs to the dictionary for all of the built-in forth words, reusing the existing XTs.
I'm warming up to this one, as it has the least side effects.  You could include the current version of your headers.asm (as another file name) so that it could be swapped in for people who need the memory, with the known side effect that it would remove the uppercase words.  This will have the side effect of listing the built-in words twice.

## Possible solution 3:
Uppercase all of Tali's built-in words.
I suspect you won't be happy about this solution, but it does solve the problem.

## Possible solution 4:
Tali's standard words are all lowercase and the manual says so with a note that this is non-standard.

## Possible solution 5:
Make Tali not case sensitive at all anymore.
You already allow ridiculously long names, so people should use them instead of i vs I and x vs X.
The gforth folks seems to think it's a good idea.  

I program in both case sensitive languages (eg. C/C++) and non case-sensitive languages (eg. Ada), and I personally prefer the non-case sensitive ones.

Thoughts?

**Comment by scotws** [comment]
_Note to self:_ After inventing the time machine, and after the traditional part about killing certain dictators, join the Forth standards committee and get this changed.

I think solution 5 seems to be best, because it uses the least resources, and it follows both the ANS standard and Gforth. 

How about this:

1. When a new word is defined, which in a lot of cases will be in less time-critical circumstances, we **lower-case everything** from A to Z and store it that way.

1. When a word is typed in, we run through the dictionary the way it is now, so that lower case words will be found as fast as possible -- which also means the built-in words, because **we leave them lower case** in the dictionary. Put differently, lower case has the fastest response time.

1. Then, if that didn't work, we copy the word someplace, and **convert every character** in the range from A to Z to lowercase. Then we run again. 

1. If that't didn't work either, we give up.

This way, the lower case built-in words are still as fast as possible. Then, if we have run through the whole dictionary, our timing is shot to hell anyway, so the extra time for copying is not that big of a deal. Converting all upper case letters to lower case follows the standard, since the built-in words will be recognized if they are typed in upper case. It will just be slower, which we can document. 

(The bartender says, "We don't serve time travelers here". A time traveler walks into a bar ...)

**Comment by SamCoVT** [comment]
I think storing the words in lowercase is fine and it's the least effort option.  Existing words already are lowercase, and we just need to lowercase new words as they are added.  The code that copies the word into the NT should be the only change there.  There should be a note in the documentation (probably in the section that describes the NT) about it.

Your code already checks the length of the name before it tries to match, so I don't think it would be that much slower to change the case, on the fly, in the A register.  The wordlist has more letters (rather than symbols or numbers) making up the words, so I can do the check for "Greater than 'Z'" first.  I think I'd prefer the slight speed penalty in exchange for much simpler code (only one search loop with no copying) and not needing a 255 byte buffer that only gets used for find-name.

Is name lookup a big performance issue?  For my uses of Tali, it would just be at startup (for the high level words) and during interactive sessions.  Once everything is in the dictionary, no names need to be looked up anymore in a non-interactive program (unless it's doing things with strings and EVALUATE).

It would be nice to figure out what the penalty might actually be - I can see why you would like a cycle count for words.  I believe that may now be possible, but I'm not sure if it works well with the existing tests.  I'll put my thoughts over in that issue.

Let me try this issue again, and you can see if you like it or not.
