### ISSUE TITLE
Test program assumes one line response for each line of test program

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#49]
This causes it to "get behind" when collecting responses that have CR in them.  Because it collects the echoed commands as well as the responses, this behaviour isn't immediately obvious unless you watch very carefully near the end of the tests.  I believe this previously caused the last test or two to not be collected into the results.  I do wonder if this might be part of the issue where you seem to be dropped to the debugger all of a sudden near the end of the tests - where you have all of the CRs in a single test word.

Some solutions might include:
Add enough blank lines at the end of the test program to allow it to catch up (one per CR used in the tests).

Have pexpect attempt to collect multiple lines, but it will have to time out to know there aren't any more.  This may slow down testing significantly, but I need to do some more research on what the possibilities are here.

**Comment by scotws** [comment]
Just off the top of my head after waking up, would it make sense to look for the "ok" or "compile" word at the end of the output instead of just collecting the next line?

**Comment by scotws** [comment]
Sure! I'll even formally assign you :-).
