### ISSUE TITLE
Add option to test program to only run specific tests

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#52]
See discussion at #46 -- this could be done as a `make` file or as part of the Python testing script (preference). Other options to the test program should include a way to silence the output, rename the output file, add an acoustic single like a beep when testing is done.

**Comment by SamCoVT** [comment]
I think adding it to the python script makes good sense.

**Comment by scotws** [comment]
Also include an option to set the time of `child.delaybeforesend()` from the command line.

**Comment by scotws** [comment]
Isolated **string** and **double** word sets so far.
