### ISSUE TITLE
CMOVE> fails simple propagation test

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#57]
**CMOVE>** should propagate characters the same way **CMOVE** does (where it works). However, it currently fails. Consider reverting to Tali Forth 1 code, which is based more directly on Leventhal.

**Comment by SamCoVT** [comment]
Your cmove> works for me (when fed a higher address as the destination)

```
Type 'bye' to exit
variable stuff 10 allot  ok
stuff 10 accept abcdefghij  ok
stuff stuff 1 + 4 cmove> stuff 10 type aabcdfghij ok
```

**Comment by SamCoVT** [comment]
I now see the propagation test you were talking about.  I think I'll have to step through it to see what's going on.  I didn't see any glaring errors in the assembly when I took a quick peek.
