### ISSUE TITLE
Can't run Tali2 in py65mon

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#58]
After doing a "git pull upstream master" I can't run Tali in py65mon:

```
$ py65mon -m 65c02 -r taliforth-py65mon.bin 
Reset with new MPU 65C02

        PC  AC XR YR SP NV-BDIZC
65C02: 0000 00 00 00 ff 00110000
Wrote +32768 bytes from $8000 to $ffff

        PC  AC XR YR SP NV-BDIZC
65C02: 0000 00 00 00 ff 00110000
Tali Forth 2 default kernel for py65mon (18. Feb 2018)


        PC  AC XR YR SP NV-BDIZC
65C02: 75e1 78 78 00 ef 00110100

Py65 Monitor

       PC  AC XR YR SP NV-BDIZC
6502: 0000 00 00 00 ff 00110000
.
```

**Comment by SamCoVT** [comment]
I've narrowed it down to your most recent commit:
f18ce0572d800629eec45a647a1bc9d5ae4be831
Added propagation tests

I tried running make to recompile, but noticed it wasn't running Ophis (because the .bin file was newer than the source files), so I did a "touch native-words.asm" and then make, and now it works.  I suspect you just need to rebuild.

**Comment by scotws** [comment]
Yeah, that seemed to have been the problem - I had tested one thing with either **CMOVE** or **CMOVE>**, I forget, and then forgot that rebuild step. Sorry. Should work now.
