### ISSUE TITLE
Add CASE, OF, ENDOF, and ENDCASE

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#62]
Forth's version of the switch/case statement is used in various tests and for that alone should probably be included. A place to start with the realization is the code at https://github.com/phf/forth/blob/master/x86/jonesforth.f (which is also in the public domain, just like Tali); the standard with the tests is at https://forth-standard.org/standard/core/CASE .

**Comment by SamCoVT** [comment]
This one looks interesting.  I'm assuming I'll need to:
edit headers.asm and build the headers for these words with COmpile and IMmediate flags.
Put the code in native_words.asm in your`comment, scope, xt_*, z_*` format.

Do these words need any other flags in the header?

I've read the jonesforth example, but I can't run that code directly because it's not for an STC forth.  The description of the behavior is good, though, and the 2012 standard seems pretty clear as well.

**Comment by scotws** [comment]
I've developed a sort of sequence for new words, which you should feel free to happily ignore, but for what it is worth (I should probably write this up in documents somewhere):

**First**, find a high-level representation, which allows me to play around with it in Gforth. In this case, Jonesforth is one source, then we have the `see` command in Gforth: 

- **CASE**: `0 constant case immediate` (not sure that **IMMEDIATE** works with Tali)
- **OF**: `: of 1+ >r 6395040 compile, 6394672 compile,  postpone if 6395048 compile, r> ; immediate` (the numbers are some executive tokens I think)
- **ENDOF**: `: endof >r  postpone else r> ; immediate` 
- **ENDCASE**: `: endcase 6395048 compile, 0  ?do postpone then loop ; immediate`

We can't directly copy Gforth because of the different licenses, and usually they do stuff differently anyway, but `see` is enormously helpful figuring out how stuff works.

**Second**, include a high-level version of the word as a Forth word. 
**Third**, add test cases. I'm at this point with **WITHIN** for example.
**Fourth**, convert to "subroutine assembler", that is, a series of JSR instructions. This is helps make sure the header information is correct. There are a bunch of math routines that are currently stuck at this stage.
**Fifth** and finally, rewrite some or all of the JSR as "direct" assembler. 

The advantage is that they are small steps, and can be done quickly, which fits my life where I only have small blocks of time here and there. 

The problem is that it takes forever. So feel free to jump right to pure assembler -- **CASE** for instance looks like something that would be best in straight code.

**Comment by scotws** [comment]
Cool, thanks. I had some weird crashes of the test routine during the first two runs somewhere in the math routines, but strangely they went away by themselves, and the machine was doing a lot in the background, so I'm just documenting it here and assuming it's something to do with the character transmission. Now I need to remember to use **CASE** :-). Thanks!
