### ISSUE TITLE
Add as many automatic tests as possible

### ISSUE THREAD

**Issue by scotws** [scotws/TaliForth2#75]
For BETA, we want all words to be either tested automatically or tested by hand. For Version 1.0, however, we want to have as many words as possible tested automatically, though that means inventing tests ourselves where ANSI doesn't provide them. 

The list of native words that are currently missing automatic tests (edit this list): **ABORT ABORT" AGAIN BOUNDS DIGIT? NUMBER 1 **(ONE)** 0 **(ZERO)** 2 **(TWO)** PICK TUCK ERASE FIND-NAME ~~MARKER~~ PARSE ? **(QUESTION)** ~~2R@~~ ~~2R>~~ ~~2>R~~ 0> 0<>**

**Comment by SamCoVT** [comment]
After breaking Tali2 (sometimes in subtle ways and other times rather obviously) trying to get :NONAME to work, I totally agree that all words should have at least one automatic test, if possible.

**Comment by scotws** [comment]
For ALPHA, I'm declaring this closed. **AGAIN** and a few other words might be candidates at some point, but for now, this is good enough.
