### ISSUE TITLE
When run in the simulator, sometimes a character is echoed twice

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#77]
I've noticed, while typing forth code directly into Tali2 running in py65mon, that every so often a character is double-echoed, as if it had been typed twice.  The second character does not make it into Tali's input buffer, so using backspace to delete the second character on the screen actually deletes the original character.  It's happened enough times that I now know to ignore it and just keep typing.  Have you seen this behavior?

I do know that py65mon has odd behavior with its input.  With copy and paste, as an example, if I highlight some text (I have copy on selection enabled) and then middle click into the terminal window running py65mon(middle click to paste,) only the first character echoes.  If I then hold down the spacebar or enter key, the pasted characters appear to Tali at my keyboard repeat rate until the paste is complete.  Then the spacebar or enter function normally.  It's as if the paste went to the STDIN buffer of py65mon fine, but the emulator won't take a character from STDIN until it sees a keypress.  I suspect this is also the reason we need that intercharacter delay in our tester.

I have not seen this double-printed character when running Tali2 on real hardware, but I also don't have a lot of time with it on real hardware, so I'm wondering if you've seen anything like the described behavior?  It happens often enough (once every 20-30 lines that I enter) that I'll probably spend some time on my hardware to make sure it really isn't there.

**Comment by scotws** [comment]
I've noticed that as well, but to be honest, it's been around so long I've stopped thinking about it, which is obviously not the right way to deal with this. I know that on "real" hardware, it can be necessary to "debounce" a key (see Leventhal), but could this be the actual problem here?

**Comment by SamCoVT** [comment]
I know the way py65mon does input is weird.  I took a glance at the code, and it looks like they turn echo off when trying to read a character and then reset it back to the default (echo on) when they are done.  They use the echo when you are at the py65mon prompt, so they don't want to just disable it all the time - only when running your program and feeding keystrokes to it.  

If you hit a letter at a time when py65mon isn't reading from the keyboard, it looks like it will be echoed.  It's non-blocking read waits up to 0.1 seconds for a key before returning, so most of the time it is checking keys, but if Tali2 hasn't read from the magic getchar location in over 0.1 seconds the character will be echoed.  When it does get around to it, the key is already there and it reads it and gives it to Tali2, where it gets echoed (again).  That's why Tali correctly only gets one copy of the key, but both the terminal and Tali2 have echoed it, so it shows two on the screen.

An quick demo of this is:
```
: delay 10000 0 do loop ;
delay
( type real fast while delay is running )
```

While I'm familiar with the C contructs Python is using (file descriptors and select), I would have to play around with it before I could consider writing better behavior.  It looks like it's not in Tali2, so it's a low priority for me at the moment - I just wanted to know if it happened to you as well, or if there was something funny on my machine.

I also see (looking at some of the test programs people are using to test py65,) that py65 is quite modular and we could invoke and feed the mpu ourselves in our test program.  This would let us feed the input directly, without delays, rather than playing games with STDIN.  It would also make it easier to add the cycle counting you wanted (#55), and allow us to remove the pexpect code (which might make the tests run on Windows too).  I may poke around a bit and see how easy/hard it is.

I see you asked about testing over on mnaberez/py65.  Let me poke and prod (at a low priority) this for a while and see if I can come up with a reasonable issue (and perhaps even a fix) for the py65mon team on this one.  Even if we move to directly instantiating the mpu in our test harness, I'd still like to see this fixed for people who just want to try out Tali2 in the emulator.

**Comment by scotws** [comment]
Sounds good. They seemed very open to suggestions ... this experience has sort of turned me into a believer with testing suites :-).

**Comment by SamCoVT** [comment]
I've got an initial test program running that is able to run py65's MPU directly and feed Tali directly from a string.  This means it will run as fast as py65 can emulate the processor, and no characters should be lost.  I need to play around with it a bit more, but my next major step will be to rewrite the existing test program to use py65 this way instead of using the pexpect method.  This also should allow the test program to be cross platform.

**Comment by SamCoVT** [comment]
I think we can close this as it's not us.

**Comment by scotws** [comment]
Good point.
