### ISSUE TITLE
Make tester run tests in the same order every time

### ISSUE THREAD

**Issue by SamCoVT** [scotws/TaliForth2#94]
The tester seems to pick whatever order it wants to run the test files.  This is annoying because the diffs on Github show entire test files removed in one section and added to another section.  I'd prefer it always run them in the same order when given no arguments (full test run) to make it easier to spot a failed test.

This might be as simple as sorting the list of tests.  I'll look into it.

**Comment by scotws** [comment]
I think this comes from me reflexively putting the test names in a set instead of a list because of speed considerations, which of course in this case is totally irrelevant.
